### PR TITLE
Adding unauthenticated empty album message. 

### PR DESCRIPTION
**Pull request by liechtym**
Adding unauthenticated empty album message + translation for text. Also added a way to toggle artifacts on demo so empty album state could be tested.

### CODE REVIEW

**Comment by liechtym** [comment]
@jshcrowthe DO NOT CLOSE BRANCH WHEN YOU MERGE!! Memories prod is dependent upon this branch!!!

**Comment by jshcrowthe** [comment]
I have talked to Bryant, and he wants to get with you on the design for this. I'll look to hear from him before we will go anywhere w/ this.

**Comment by liechtym** [comment]
He is wanting to change the design? This is an implementation of his mockup.

**Comment by jshcrowthe** [comment]
LGTM 👍

**Comment by liechtym** [comment]
Thanks!

**Pull request merged**
